#! /bin/bash

. ~/til/bash/confirm

. ~/til/svn/svn_wc_base_url.sh

[ $# -eq 0 ] && echo "Please supply a flyspray task number!" && exit 1

svn info > /dev/null 2>&1
[ $? -ne 0 ] && echo "Not a Subversion working copy, exiting." && exit 1

BRANCH_NUMBER="$1"

if [ "$BRANCH_NUMBER" = "-" ]; then
	BRANCH_NUMBER=$(cat ~/.svn_last_branch.tmp)
fi

function switchBranch()
{
	SvnWcBaseUrl=$(svn_wc_base_url.sh)

	if [ $1 = "trunk" ]; then
		svn switch "$SvnWcBaseUrl/trunk" 2> /dev/null
	else
		svn switch "$SvnWcBaseUrl/branches/FS%20$1"
	fi
}

### Main

LastBranch=$(svn_current_branch.sh)

IsNexusEnv=$( pwd | grep "nexus" | wc -c)

switchBranch "$BRANCH_NUMBER"


if [ $? -ne 0 ]; then

	echo ""
	echo -n "Couldn't switch to the branch, create it instead?"

	Confirm

	if [ $Confirm -eq 0 ]; then  # We decided to create a new branch
		svn_branch.sh "$BRANCH_NUMBER"

	else
		echo "Exiting" && exit 1
	fi

	if [ $? -ne 0 ]; then  # Branch creation failed
		echo "Branch creation failed, something has gone horribly wrong."
		exit 1
	else  # We created a new branch and are switching to it
		switchBranch "$BRANCH_NUMBER"
		echo $LastBranch > ~/.svn_last_branch.tmp

		# Do some busywork for nexus environments
		[ $IsNexusEnv -gt 0 ] && ~/til/nexus/createEnv.sh "$BRANCH_NUMBER"
	fi
else  # we sucessfully switched, write the last branch number out
		echo $LastBranch > ~/.svn_last_branch.tmp
fi


# Finally, whatever the result, update the branch we're currently on
svn info | grep "Relative URL" | rev | cut -c -5 | rev > ./.current_branch
