#! /bin/bash

[ $# -eq 0 ] && echo "Please supply a flyspray task number!" && exit 1


function switchBranch()
{
	svn switch "http://svn.excelsystems.com/svn/websmart/websmart/branches/FS $1" 2> /dev/null
}

switchBranch "$1"

if [ $? -ne 0 ]; then
	echo "Couldn't switch to the branch, attempting to create it instead."
	powershell svn_branch.ps1 "$1"

	if [ $? -ne 0 ]; then
		echo "Branch creation failed, something has gone horribly wrong."
		exit 1
	else
		switchBranch "$1"
	fi

fi
