#! /bin/bash


function Confirm {
	echo -n " (y|n) "

	read

	if [[ "$REPLY" == "y" || "$REPLY" == "Y" || "$REPLY" == "yes" ]]; then
		Confirm=0
	fi

	if [[ "$REPLY" == "n" || "$REPLY" == "N" || "$REPLY" == "no" ]]; then
		Confirm=1
	fi
}
